GET http://127.0.0.1:5000/generate
    ?title=Agile Project Micromanagement
    &topText=Cognitive Dissonance as "Process"
    &author=@denitdao
    &image_code=2
    &theme=6
    &guide_text_placement=bottom_right
    &guide_text=Water-Fall with Stand-ups

###