GET http://127.0.0.1:5000/generate
    ?title=Error - Driven Development
    &topText=Try, Catch, print("Hello World")
    &author=u/ashemark2
    &image_code=41
    &theme=6
    &guide_text_placement=bottom_right
    &guide_text=The Definitive Guide

###